modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      follow_redirects: true
      valid_http_versions:
        - "HTTP/1.1"
        - "HTTP/2"
        - "HTTP/2.0"        
      valid_status_codes:
        - 200
        - 401
      preferred_ip_protocol: "ip4"
      tls_config:
          ca_file: /etc/blackbox_exporter/certs/caddy-root.crt 
cat: cat: No such file or directory
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # default = 2xx
      method: GET
