global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "radicale_blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://dav.home.koko
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      # Nice-to-have: instance label becomes the probed target
      - source_labels: [__param_target]
        target_label: instance

      # Where Prometheus actually scrapes: the blackbox exporter
      - target_label: __address__
        replacement: expdav.home.koko:9115
